cluster:
  namespace: prod

image:
  tag: "@sha256:97934dfc33064115468dfc2c03c06cf514898dd8bea6a9ad5d206d6be73916f5"

awsSettings:
  iamRole: prod-email-service-sa
  region: us-west-2

datadog:
  enabled: true
  traceSampleRate: "0.1"
  logsInjection: "true"

appSettings:
  javaOpts: "-javaagent:/opt/datadog/dd-agent.jar -Dconfig.file=/var/lib/gen_config/application_gen.conf -XX:+UseG1GC -Xms512m -Xmx1664m"
  exampleSecretId: prod-email-secret-shhhh
  replicas: 3
  db:
    hostname: prod-email-rds
    password: prod-email-db-password
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "2000m"
      memory: "2Gi"

configMap:
  preserveOldReleases: true

argoStrategy:
  canary:
    antiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        weight: 1
    maxSurge: "100%"
    maxUnavailable: "0"
    steps:
      - setWeight: 10
      - pause: { }
      - setWeight: 50
      - pause: { }
