cluster:
  namespace: qa2

image:
  tag: "@sha256:97934dfc33064115468dfc2c03c06cf514898dd8bea6a9ad5d206d6be73916f5"

awsSettings:
  accessKey: qa2-access-key
  secretKey: qa2-secret
  region: us-west-2

appSettings:
  replicas: 2
  secretsMgrKeyID: qa2-TEMPLATE_SVC_BASE
  db:
    hostname: qa2-TEMPLATE_SVC_BASE-rds
    password: qa2-TEMPLATE_SVC_BASE-db-password
